name: CI for CMake

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake_ubuntu2204.yml"
      
jobs:
  
  linux:
    runs-on: ubuntu-22.04
    name: CMake build on linux
    timeout-minutes: 30
    
    steps:
      - name: Install system dependencies
        run: |
         sudo apt-get update -yq
         sudo apt-get install -yq --no-install-recommends libmpich-dev mpich
    
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: CMake configure
        run: |
          DIR="cmake_build" && mkdir -p "$DIR" && cd "$DIR"
          cmake ..
    
